# APPNICENAME=Stash
# APPDESCRIPTION=An organizer for your porn, written in Go
services:
  stashPro:
    image: stashapp/stash:latest
    container_name: stashApp-pro
    restart: unless-stopped
    ## the container's port must be the same with the STASH_PORT in the environment section
    ports:
      - "9001:9001"
    ## If you intend to use stash's DLNA functionality uncomment the below network mode and comment out the above ports section
    # network_mode: host
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "2m"
    environment:
      - STASH_STASH=/data/
      - STASH_GENERATED=/generated/
      - STASH_METADATA=/metadata/
      - STASH_CACHE=/cache/
      ## Adjust below to change default port (9999)
      - STASH_PORT=9001
    volumes:
      - /mnt/stashpro_data/mystuff:/etc/hostfiles

      - /etc/localtimePro:/etc/localtime:ro
      ## Adjust below paths (the left part) to your liking.
      ## E.g. you can change ./config:/root/.stash to ./stash:/root/.stash
      
      ## Keep configs, scrapers, and plugins here.
      - /mnt/stashpro_data/config:/root/.stash
      ## Point this at your collection.
      - /mnt/stashpro_data/data:/data
      ## This is where your stash's metadata lives
      - /mnt/stashpro_data/metadata:/metadata
      ## Any other cache content.
      - /mnt/stashpro_data/cache:/cache
      ## Where to store binary blob data (scene covers, images)
      - /mnt/stashpro_data/blobs:/blobs
      ## Where to store generated content (screenshots,previews,transcodes,sprites)
      - /mnt/stashpro_data/generated:/generated

# APPNICENAME=StashPersonal
# APPDESCRIPTION=An organizer for your porn, written in Go


  stashPersonal:
    image: stashapp/stash:latest
    container_name: stashApp2-Personal
    restart: unless-stopped
    ## the container's port must be the same with the STASH_PORT in the environment section
    ports:
      - "9002:9002"
    ## If you intend to use stash's DLNA functionality uncomment the below network mode and comment out the above ports section
    # network_mode: host
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "2m"
    environment:
      - STASH_STASH=/data/
      - STASH_GENERATED=/generated/
      - STASH_METADATA=/metadata/
      - STASH_CACHE=/cache/
      ## Adjust below to change default port (9999)
      - STASH_PORT=9002
    volumes:
      - /mnt/stashpersonal_data/mystuff:/etc/hostfiles

      - /etc/localtimePersonal:/etc/localtime:ro
      ## Adjust below paths (the left part) to your liking.
      ## E.g. you can change ./config:/root/.stash to ./stash:/root/.stash
      
      ## Keep configs, scrapers, and plugins here.
      - /mnt/stashpersonal_data/config:/root/.stash
      ## Point this at your collection.
      - /mnt/stashpersonal_data/data:/data
      ## This is where your stash's metadata lives
      - /mnt/stashpersonal_data/metadata:/metadata
      ## Any other cache content.
      - /mnt/stashpersonal_data/cache:/cache
      ## Where to store binary blob data (scene covers, images)
      - /mnt/stashpersonal_data/blobs:/blobs
      ## Where to store generated content (screenshots,previews,transcodes,sprites)
      - /mnt/stashpersonal_data/generated:/generated

# APPNICENAME=StashAppProVR
# APPDESCRIPTION=VR Viewer for your VR porn to work with StashApp
  stash-vr:
    image: ofl0w/stash-vr:latest
    container_name: stash-vr
    restart: unless-stopped
    ports:
      - "9666:9666"
    environment:
      STASH_GRAPHQL_URL: "http://127.0.0.1:9001/graphql"
      STASH_API_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJrZGFzc293Iiwic3ViIjoiQVBJS2V5IiwiaWF0IjoxNzQyODQwNzQ4fQ.dCFQQB5ya8_CcZdFLx8reajhiyzZ3sZgBZiTGsUm3Vc"
      #FAVORITE_TAG: "FAVORITE"

      ## FILTERS can be either 'frontpage' or a comma separated list of filter ids.
      ## If left empty all saved filters will be shown.
      #FILTERS: "2,3,7"     # comma separated list of filter ids to show
      #FILTERS: "frontpage" # show only scene filters from front page

      #ALLOW_SYNC_MARKERS: "true"
      #DISABLE_HEATMAP: "true"
      #HEATMAP_HEIGHT_PX: 45
      #DISABLE_PLAY_COUNT: "true"
      #EVENT_SERVER_URL: "http://192.168.0.127:8099":"

      #LOG_LEVEL: "debug"

      #FORCE_HTTPS: "true"
